spring.application.name=dew-lingo-be
spring.jpa.hibernate.ddl-auto=validate

spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
